server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false   # Do not register this service itself
    fetch-registry: false         # Do not fetch registry information
