server:
  port: 8001

spring:
  application:
    name: bookmark-service
  data:
    rest:
      base-path: /api
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    platform: h2

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

---
spring:
  profiles: dev

eureka:
  client:
    enabled: false

---
spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bookmarks
    username: postgres
    password: # Is set in Cloud Config properties
    platform: postgres
