server:
  port: 8001

spring:
  application:
    name: bookmark-service
  data:
    rest:
      base-path: /api
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    platform: h2

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

security:
  oauth2:
    resource:
      token-info-uri: ${OAUTH_TAKEN_URI:http://localhost:8081/oauth/check_token}
    client:
      clientId: ${CLIENT_ID:ce920188d47a2f51d7c6}
      clientSecret: ${CLIENT_SECRET:8b562ac7f64785c96a5d207f4a6cc13725a06cbb}

---
spring:
  profiles: dev

logging:
  level:
    web: DEBUG
    org:
      springframework:
        security: DEBUG

eureka:
  client:
    enabled: false

---
spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bookmarks
    username: postgres
    password: # Is set in Cloud Config properties
    platform: postgres
